development:
  host: localhost
  database: noshspot_dev

test:
  host: localhost
  database: noshspot_test

# set these environment variables on your prod server
production:
  uri: <%= ENV['MONGOLAB_URI'] %>